apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dealership
  name: dealership
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
      - image: us.icr.io/${SN_ICR_NAMESPACE}/dealership:latest
        imagePullPolicy: Always
        name: dealership
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dealership
  namespace: default
spec:
  type: NodePort
  selector:
    run: dealership
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
